version: "3.8"
services:
  gluetun:
    image: qmcgaw/iptables
    container_name: iptables
    cap_add:
      - NET_ADMIN
    network_mode: host
    volumes:
      ./rules.sh:/rules.sh:ro
    restart: unless-stopped
